# Generated by Django 5.0.1 on 2024-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='heeee', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
